# Generated by Django 4.2.28 on 2026-03-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_remove_notificationsettings_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('context', models.CharField(blank=True, help_text='High-level source, e.g. bill_pdf, bill_text, report_pdf.', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('green', 'Green API'), ('cloud', 'WhatsApp Cloud API'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
