# Generated by Django 4.2.28 on 2026-02-23 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_new_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_company_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client/owner for this project (for client portal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('photo_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_photos', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-photo_date', '-created_at'],
            },
        ),
    ]
