# Generated by Django 4.2.28 on 2026-02-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '__first__'),
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount_in_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Converted value in PKR if currency is not PKR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='parties.party'),
        ),
        migrations.AddField(
            model_name='contractpaymentschedule',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contractpaymentschedule',
            name='retention_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractpaymentschedule',
            name='wht_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
