# Generated by Django 4.2.28 on 2026-02-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_amount_in_pkr_contract_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpaymentschedule',
            name='wht_certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contractpaymentschedule',
            name='wht_tax_period',
            field=models.CharField(blank=True, help_text='e.g. 2024-01 for Jan 2024', max_length=20),
        ),
    ]
