# Generated by Django 4.2.28 on 2026-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_add_missing_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='retention_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 5 for 5%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_release_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days after completion to release retention', null=True),
        ),
    ]
