# Generated by Django 4.2.28 on 2026-02-25 23:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_add_new_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Estimate title e.g. Main Building BOQ', max_length=200)),
                ('version', models.CharField(blank=True, help_text='e.g. v1, Rev 2', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('estimate_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overhead % (e.g. 10 for 10%)', max_digits=5)),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Contingency % (e.g. 5 for 5%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
            ],
            options={
                'ordering': ['-estimate_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('earthwork', 'Earthwork'), ('concrete', 'Concrete'), ('brickwork', 'Brickwork / Blockwork'), ('steel', 'Steel / Reinforcement'), ('plaster', 'Plaster & Pointing'), ('flooring', 'Flooring & Tiling'), ('roofing', 'Roofing'), ('finishes', 'Finishes & Painting'), ('sanitary', 'Sanitary & Plumbing'), ('electrical', 'Electrical'), ('mep', 'MEP / HVAC'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unit', models.CharField(choices=[('sft', 'Square Feet (sft)'), ('sqm', 'Square Metre (sqm)'), ('cft', 'Cubic Feet (cft)'), ('cum', 'Cubic Metre (cum)'), ('rft', 'Running Feet (rft)'), ('rm', 'Running Metre (rm)'), ('no', 'Number (no.)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('marla', 'Marla'), ('lump_sum', 'Lump Sum')], default='no', max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
