# Generated by Django 4.2.28 on 2026-02-25 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_new_features'),
        ('projects', '0004_add_new_features'),
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Owner company (set for standalone scenarios; legacy estimates may have only project)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='core.company'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(help_text='Scenario name e.g. Main Building BOQ, Option A', max_length=200),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project'),
        ),
    ]
