# Generated by Django 4.2.28 on 2026-02-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_new_features'),
        ('estimates', '0002_standalone_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='e.g. lahore, karachi', max_length=50)),
                ('construction_type', models.CharField(choices=[('grey_structure', 'Grey Structure'), ('complete', 'Complete')], max_length=30)),
                ('construction_mode', models.CharField(choices=[('with_material', 'With Material'), ('without_material', 'Without Material')], max_length=30)),
                ('rate_per_sft', models.DecimalField(decimal_places=2, help_text='PKR per square foot', max_digits=12)),
                ('effective_date', models.DateField(help_text='Date from which this rate applies')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = system default; set = merchant-specific rate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_rates', to='core.company')),
            ],
            options={
                'ordering': ['city', 'construction_type', 'construction_mode'],
                'unique_together': {('company', 'city', 'construction_type', 'construction_mode')},
            },
        ),
    ]
