# Generated by Django 4.2.28 on 2026-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_seed_default_construction_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionrate',
            name='rate_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max of range Rs/sft for display', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='constructionrate',
            name='rate_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min of range Rs/sft for display', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='constructionrate',
            name='construction_mode',
            field=models.CharField(choices=[('with_material', 'With Materials (Contractor + Materials)'), ('without_material', 'Without Materials (Labour Only)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='constructionrate',
            name='construction_type',
            field=models.CharField(choices=[('grey_structure_only', 'Grey Structure Only'), ('complete_standard', 'Complete House – Standard Finish'), ('complete_mid_range', 'Complete House – Mid-Range Finish'), ('complete_premium', 'Complete House – Premium Finish')], max_length=30),
        ),
        migrations.AlterField(
            model_name='constructionrate',
            name='rate_per_sft',
            field=models.DecimalField(decimal_places=2, help_text='PKR per sq.ft (used for calculation; midpoint if range)', max_digits=12),
        ),
    ]
