from io import BytesIO

from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend
from django.http import HttpResponse

from audit.log import log
from notifications.models import Notification
from notifications.utils import send_notification_whatsapp, send_whatsapp_document_bytes
from .models import FundTransfer
from .serializers import FundTransferSerializer


class FundTransferListCreateView(generics.ListCreateAPIView):
    serializer_class = FundTransferSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ('from_project', 'to_project')

    def get_queryset(self):
        qs = FundTransfer.objects.select_related('from_project', 'to_project')
        if getattr(self.request.user, 'company_id', None):
            qs = qs.filter(from_project__company_id=self.request.user.company_id)
        return qs

    def perform_create(self, serializer):
        obj = serializer.save()
        log(
            self.request.user,
            'fund_transfer',
            'FundTransfer',
            obj.id,
            {'amount': str(obj.amount), 'from_project': obj.from_project_id, 'to_project': obj.to_project_id, 'date': str(obj.transfer_date)},
            self.request,
        )
        n = Notification.objects.create(
            user=self.request.user,
            notification_type=Notification.NotificationType.FUND_TRANSFER,
            title='Fund transfer completed',
            message=f'Transferred Rs {obj.amount} from {obj.from_project.name} to {obj.to_project.name}.',
            link='/transfers',
        )
        send_notification_whatsapp(self.request.user, n.title, n.message, n.link, channel='transfers')


class FundTransferDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = FundTransferSerializer

    def get_queryset(self):
        qs = FundTransfer.objects.select_related('from_project', 'to_project')
        if getattr(self.request.user, 'company_id', None):
            qs = qs.filter(from_project__company_id=self.request.user.company_id)
        return qs

    def perform_update(self, serializer):
        obj = serializer.save()
        log(self.request.user, 'update_transfer', 'FundTransfer', obj.id, {}, self.request)

    def perform_destroy(self, instance):
        tid = instance.id
        instance.delete()
        log(self.request.user, 'delete_transfer', 'FundTransfer', tid, {}, self.request)


def _build_transfer_receipt_pdf_bytes(transfer: FundTransfer) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    title = 'Cash Transfer Receipt'
    elements.append(Paragraph(title, styles['Title']))
    elements.append(Spacer(1, 12))

    from_name = getattr(transfer.from_project, 'name', transfer.from_project_id)
    to_name = getattr(transfer.to_project, 'name', transfer.to_project_id)

    info_data = [
        ['From project', from_name],
        ['To project', to_name],
        ['Amount', f"Rs {float(transfer.amount):,.2f}"],
        ['Date', str(transfer.transfer_date)],
        ['Notes', transfer.notes or ''],
    ]
    table = Table(info_data, hAlign='LEFT', colWidths=[120, 360])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor('#e5e7eb')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 18))
    elements.append(Paragraph('<font size="9" color="#6b7280">Generated by Construx360</font>', styles['Normal']))

    doc.build(elements)
    return buffer.getvalue()


class FundTransferReceiptPDFView(APIView):
    """Generate a PDF receipt for a single fund transfer (download)."""
    permission_classes = [IsAuthenticated]

    def get(self, request, pk):
        try:
            transfer = FundTransfer.objects.select_related('from_project', 'to_project').get(pk=pk)
        except FundTransfer.DoesNotExist:
            return Response({'detail': 'Transfer not found.'}, status=404)

        if getattr(request.user, 'company_id', None):
            if getattr(transfer.from_project, 'company_id', None) != request.user.company_id:
                return Response({'detail': 'Not found.'}, status=404)

        pdf_bytes = _build_transfer_receipt_pdf_bytes(transfer)
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename=transfer-{transfer.id}.pdf'
        return response


class FundTransferSendReceiptWhatsAppView(APIView):
    """POST to send this transfer receipt PDF to the current user's WhatsApp."""
    permission_classes = [IsAuthenticated]

    def post(self, request, pk):
        try:
            transfer = FundTransfer.objects.select_related('from_project', 'to_project').get(pk=pk)
        except FundTransfer.DoesNotExist:
            return Response({'detail': 'Transfer not found.'}, status=404)

        if getattr(request.user, 'company_id', None):
            if getattr(transfer.from_project, 'company_id', None) != request.user.company_id:
                return Response({'detail': 'Not found.'}, status=404)

        phone = (getattr(request.user, 'phone', None) or '').strip()
        if not phone:
            return Response({'detail': 'No WhatsApp phone set on your user profile.'}, status=400)

        pdf_bytes = _build_transfer_receipt_pdf_bytes(transfer)
        caption = f"Cash transfer – Rs {transfer.amount} from {transfer.from_project.name} to {transfer.to_project.name} on {transfer.transfer_date}."
        ok = send_whatsapp_document_bytes(phone, pdf_bytes, f"transfer-{transfer.id}.pdf", caption=caption)
        if not ok:
            return Response({'detail': 'Failed to send via WhatsApp. Check server WhatsApp configuration.'}, status=502)
        return Response({'detail': 'Transfer receipt sent to WhatsApp.'})
