# Generated by Django 4.2.28 on 2026-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='performance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='performance_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 rating', null=True),
        ),
    ]
