# Generated by Django 4.2.28 on 2026-02-23 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_add_new_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittal_number', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('submittal_type', models.CharField(choices=[('material', 'Material Sample'), ('method', 'Method Statement'), ('shop_drawing', 'Shop Drawing'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision Required')], default='draft', max_length=20)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submittals_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
