# Generated by Django 4.2.28 on 2026-02-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='projects.project')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='projects.project')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
