# Generated by Django 4.2.28 on 2026-02-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_company_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('drawing', 'Drawing'), ('boq', 'BOQ'), ('variation', 'Variation'), ('noc', 'NOC'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=20)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_docs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
