# Generated by Django 4.2.28 on 2026-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='revision',
            field=models.CharField(blank=True, help_text='e.g. Rev A, 1.0', max_length=50),
        ),
    ]
