# Generated by Django 4.2.28 on 2026-02-25 15:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_add_new_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Optional employee code or file number.', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, help_text='e.g. Site Engineer, Supervisor', max_length=150)),
                ('department', models.CharField(blank=True, help_text='e.g. Site, Accounts, HR', max_length=150)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('daily_wage', 'Daily wage')], default='full_time', max_length=20)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='monthly', help_text='How base pay is defined (monthly, hourly, or daily).', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Base salary amount (per month / hour / day, depending on salary type).', max_digits=12)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cnic', models.CharField(blank=True, help_text='CNIC or national ID', max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(help_text='1-12 (Jan–Dec)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='core.company')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total of house, fuel, phone, etc.', max_digits=12)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rate per overtime hour.', max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('advance_recovery', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly recovery of salary advance (deduction).', max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Final payable amount after all adjustments.', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='employees.payrollperiod')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
