# Generated by Django 4.2.28 on 2026-02-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_new_features'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_project',
            field=models.ForeignKey(blank=True, help_text='If set, salaries will be booked to this project as "Labor" expense when payroll is paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_employees', to='projects.project'),
        ),
    ]
